{
OUT
3
10
10
2
3.0
3.0
3.0
3.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
-1
8
-8
0
-1.0
-1.0
-1.0
-1.0
-4.0
-4.0
4.0
4.0
-4.0
-4.0
4.0
4.0
2
9
9
1
2.0
2.0
2.0
2.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
3/2
1.5
1.5
1.5
3/2
1.5
1.5
1.5
3
2
-30
30
-30.0
-30.0
-2/3
}

;addition
print str(1+2)
print str(9+true)
print str(true+9)
print str(true+true)

print str(1.0+2.0)
print str(1.0+2.0f)
print str(1.0f+2.0)
print str(1.0f+2.0f)

print str(1+5.0)
print str(1+5.0f)
print str(5.0+1)
print str(5.0f+1)

print str(true+5.0)
print str(true+5.0f)
print str(5.0+true)
print str(5.0f+true)

;subtraction
print str(1-2)
print str(9-true)
print str(true-9)
print str(true-true)

print str(1.0-2.0)
print str(1.0-2.0f)
print str(1.0f-2.0)
print str(1.0f-2.0f)

print str(1-5.0)
print str(1-5.0f)
print str(5.0-1)
print str(5.0f-1)

print str(true-5.0)
print str(true-5.0f)
print str(5.0-true)
print str(5.0f-true)

;multiplication
print str(1*2)
print str(9*true)
print str(true*9)
print str(true*true)

print str(1.0*2.0)
print str(1.0*2.0f)
print str(1.0f*2.0)
print str(1.0f*2.0f)

print str(1*5.0)
print str(1*5.0f)
print str(5.0*1)
print str(5.0f*1)

print str(true*5.0)
print str(true*5.0f)
print str(5.0*true)
print str(5.0f*true)

;division
print str(3/2)
print str(3/2.0)
print str(3.0/2)
print str(3.0/2.0)

print str(3/2)
print str(3/2.0f)
print str(3.0f/2)
print str(3.0f/2.0f)

;integer division
print str(20//6)

;remainder
print str(20%6)

;negate
print str(-30)
print str(-(-30))
print str(-30.0)
print str(-30.0f)
print str(-2/3)

assert -(-100)==100

;comparison
;assert cmp(10,20)==-1
